### ISSUE TITLE
code.jquery.com use a TLS/SSL certificate no more valid

### ISSUE THREAD

**Issue by fcomte** [jquery/codeorigin.jquery.com#59] opened 2020-05-31 23:02 UTC
The root certificate authority has expired at 30 may 2020

https://www.ssllabs.com/ssltest/analyze.html?d=code.jquery.com&s=2001%3a4de0%3aac19%3a0%3a0%3a1%3ab%3a1b&latest

**Comment by brianwarner** [comment] 2020-06-01 02:40
Thanks for raising this, @fcomte. This appears to be a general issue affecting the legacy AddTrust root cert, which was replaced in 2010 by the COMODO RSA Certification Authority. As long as a browser/OS has an alternate path to establish the chain of trust (meaning that the cert store has been updated since 2010), this shouldn't cause SSL failures.

In the event that it does affect a system, it will likely affect a great many of the client's SSL connections.

https://www.xolphin.com/support/Rootcertificates/Phasing_out_Addtrust_External_CA_Root_certificate

**Comment by mgol** [comment] 2020-06-01 07:02
Closing per Brian’s comment.

**Comment by Patate687** [comment] 2020-06-01 19:01
This should not be closed, seems like your ADC(ngnix?) is forcing a link to the old CA Root certificate.

![image](https://user-images.githubusercontent.com/66273770/83443138-42caa000-a417-11ea-8e9b-2e887656a037.png)

We have no problem with _https://jquery.org_ which expose the same certificate as you do on _**code.jquery.org**_ The CA Root certificate sent on this exposure is Good
![image](https://user-images.githubusercontent.com/66273770/83443522-e1570100-a417-11ea-8e36-24f1368ebd3b.png)

Also, for improvement, I would recommand you to not send the CA Root Certificate in chain certificate and let the servers discovers them by themself. Can't find the right link to the documentation about that, will update as soon as I get it.

**Comment by mgol** [comment] 2020-06-02 09:27
@brianwarner the number of duplicates & comments like the one above by @Patate687 suggest to me the issue affects more than just very old systems.

I’ll reopen it for now for further investigation & to reduce the number of duplicates a bit as people are more likely to look at open issues.

**Comment by Patate687** [comment] 2020-06-02 12:20
More info on full chain : https://discussions.qualys.com/docs/DOC-1931

`Certificate chains that are too long; Sites often include more certificates in the handshake than necessary. Of those, most include one extra certificate, and that is the actual trusted root certificate (which browsers already have in their storage). This last certificate is not needed for the validation process. Having an additional certificate in the chain wastes bandwidth and decreases overal performance slightly. A small number of sites will include a very large number of certificates as a result of misconfiguration. Such sites will typically suffer significant performance issues and need to be reconfigured.`

**Comment by armyofda12mnkeys** [comment] 2020-06-02 15:02
One of our websites was down because of this. The Enterprise Network Firewall was blocking the jquery resource since it had a 'invalid cert' higher up on the cert chain. 
Temporarily for now, our network-admin has put jquery.com on a whitelist but will watch this issue to see when the issue is fixed so we can remove that one-off rule.

**Comment by Patate687** [comment] 2020-06-02 18:50
Just to add to this, your vloudflare configuration is sending the good ca root certificate but not the ngnix exposing this website...

**Comment by brianwarner** [comment] 2020-06-02 19:58
Thank you @Patate687 and @armyofda12mnkeys, I'm on this and will track down the fix asap.

**Comment by bigben386** [comment] 2020-06-02 20:52
Can you please make sure there are no expired intermediate certs in the chain too? This also causes issues for us. Thanks.

**Comment by brianwarner** [comment] 2020-06-02 23:08
Folks, I believe this is taken care of. I've scrubbed the expired intermediary (the source of the original issue). Please let me know if you still see issues.

https://www.ssllabs.com/ssltest/analyze.html?d=code.jquery.com&s=2001%3a4de0%3aac19%3a0%3a0%3a1%3ab%3a1b&latest

**Comment by Patate687** [comment] 2020-06-02 23:16
Holy cow! I think you did removed the link to the root CA dont you? 😁

**Comment by brianwarner** [comment] 2020-06-02 23:22
The new trust chain is `jQuery cert` (the cert) -> `COMODO RSA Domain Validation Secure Server CA` (distributed in the chain) -> `COMODO RSA Certification Authority` (in the system/browser/etc. trust store)

**Comment by Patate687** [comment] 2020-06-03 00:27
Cool, will this works for blogs.jquery.com|org too?

**Comment by brianwarner** [comment] 2020-06-03 02:30
Hmm, I think that's independent of this. I'll have a chat with @mgol about it.

**Closed** 2020-07-15 00:49 UTC
