### ISSUE TITLE
One of the root or intermediate certificates has expired (3 days ago).

### ISSUE THREAD

**Issue by JakeCigar** [jquery/codeorigin.jquery.com#60] opened 2020-06-01 13:56 UTC
https://www.sslshopper.com/ssl-checker.html#hostname=https://code.jquery.com reports an error.

And

https://sectigostore.com/ssl-tools/ssl-checker.php does not. 

https://forum.jquery.com/topic/certificate-chain-issue reported it to the forum.
![image](https://user-images.githubusercontent.com/1222843/83416061-f65e7080-a3d4-11ea-8ba8-66aca69a1bfc.png)

**Comment by mgol** [comment] 2020-06-01 15:34
Duplicate of #59.

**Closed by mgol** 2020-06-01 15:34 UTC
