### ISSUE TITLE
code.jquery.com produces different script tag based on how it is accessed

### ISSUE THREAD

**Issue by paulsmithkc** [jquery/codeorigin.jquery.com#55] opened 2019-11-14 14:56 UTC
If you go to **https:**//code.jquery.com and request a script tag, it will load the script over https.

<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

<br/>However, if you just navigate to the website via the address bar or google, you will get the HTTP website instead (**http:**//code.jquery.com). This version of the website produces incorrect code that points to HTTP website. This is completely non-obvious to the developer and leads to jQuery not being loaded properly over HTTPS.

Please fix this so both versions of the website provide script links that point to **https:**//code.jquery.com

**Comment by Krinkle** [comment] 2020-07-04 23:28
Confirmed via <https://code.jquery.com/qunit/> vs <http://code.jquery.com/qunit/>.

**Comment by Krinkle** [comment] 2020-07-15 01:08
I'd prefer not to complicate or hardcode in the UI code for code.jquery.com which protocol to use (also because it makes local testing harder). I'm closing this in favour of https://github.com/jquery/codeorigin.jquery.com/issues/63, which effectively solves the same issue.

**Closed by Krinkle** 2020-07-15 01:08 UTC
Labels: problem
