### ISSUE TITLE
ERR_CONNECTION_RESET on code.jquery.com

### ISSUE THREAD

**Issue by Eahlstan** [jquery/codeorigin.jquery.com#80] opened 2021-11-15 01:11 UTC
Greetings.

When I try to connect to code.jquery.com I get that error.
I tried it on Chrome, Edge and Firefox and they all do the same (I never use Edge or Firefox, so they are 100% clean without any addons). Now the really strange thing is that when I change the language in those browsers (not my system language) from German to English everything works and when I set it back from English to German it resets the connection again.

I can ping the site and trace the route without problems:

```
  1     2 ms     1 ms     2 ms  2a02-8388-0a84-de80-362c-c4ff-fe30-17c3.cable.dynamic.v6.surfer.at [2a02:8388:a84:de80:362c:c4ff:fe30:17c3] 
  2    12 ms    10 ms     8 ms  2a02:8382:0:24::1 
  3     8 ms     9 ms     8 ms  at-vie-sk11-pe06-bundle-ether608-6.v6.aorta.net [2a02:8380:100:6e::1] 
  4     8 ms     *       11 ms  2a02:8386::1:47:0 
  5    10 ms     9 ms     9 ms  2003:0:fe00:e::1 
  6     *        *        *     Zeitberschreitung der Anforderung.
  7    21 ms    22 ms    20 ms  2003:0:1304:8004::2 
  8    20 ms    20 ms    26 ms  2001:4de0:ac18::1:a:1a 
```
Trying to open https://code.jquery.com/jquery-2.1.4.min.js results in these two:
![Screenshot 2021-11-15 012621](https://user-images.githubusercontent.com/59618179/141707232-3b345a6a-5f64-47fd-b707-48fa6f7d9a5a.JPG)
![Screenshot 2021-11-15 012556](https://user-images.githubusercontent.com/59618179/141707233-50862746-7b53-48e9-b01d-af95cd713dce.JPG)

Anyone knows why the connection is denied only when my browsers are set to German?

Thank you.

**Comment by Eahlstan** [comment] 2021-11-25 14:14
I just forced Firefox to use IPv4 on code.jquery.com
Using IPv4 I can access the site, using IPv6 causes ERR_CONNECTION_RESET - but still only when my browsers are set to german.

**Comment by motyc** [comment] 2021-12-23 11:51
Also +1, see also https://github.com/jquery/codeorigin.jquery.com/issues/77#issuecomment-1000249204

**Comment by rmcolbert** [comment] 2022-01-06 00:14
+1 for users trying to consume Constant Contact email forms. https://code.jquery.com/jquery-3.4.1.min.js fails to load w/ ERR_CONNECTION_RESET and then suddenly starts loading. Seems like an issue w/ the official StackPath CDN hosting.

**Comment by CratesDeThebes** [comment] 2022-01-25 14:09
+1, my browsers are set in french and in english. A good test on my side : 

- `curl -6 https://code.jquery.com/jquery-3.4.1.min.js -I -v` > Fail (Connection reset by peer, err 104)

- `curl -4 https://code.jquery.com/jquery-3.4.1.min.js -I -v` > Success

**Comment by oppipp** [comment] 2022-02-24 00:50
I'm from Japan and I can't IPv6 connect to https://code.jquery.com/

**Comment by bdoserror** [comment] 2022-02-28 23:42
I'm indirectly having this issue too, trying to access the [James Webb Space Telescope site](https://webb.nasa.gov/content/webbLaunch/whereIsWebb.html?units=metric), and it's failing to load JQuery, and it looks like this bug. If I turn off my ethernet connection and switch to Wifi, it works.

**Comment by MackSix** [comment] 2022-03-01 05:44
It happens to me too.

Putting the ipv4s in the HOSTS file allows me to connect. 

This is specific to 2 Dell Alienware PCs. One an R11 (2020) with Windows 10 and an R10 (2021) with Windows 11. They both have a Killer(R) Wi-Fi 6 AX1650x 160MHz Wireless Network Adapter (200NGW).

I have an older HP, from 2017, with Windows 10 that works fine on the same AT&T DSL connection.

**Comment by MackSix** [comment] 2022-03-01 06:46
It happens to me too.

Putting the IPv4s in the HOSTS file allows me to connect.

This is specific to 2 Dell Alienware PCs. One an R11 (2020) with Windows 10 and an R10 (2021) with Windows 11. They both have a Killer(R) Wi-Fi 6 AX1650x 160MHz Wireless Network Adapter (200NGW).

I have an older HP, from 2017, with Windows 10 and all the IPv6 work fine on the same AT&T DSL connection in Kansas City.

On the Alienwars, ```2001:4de0:ac18::1:a:2b``` doesn't work at all and the other IPs, I keep reloading browser with Ctrl+F5 and they sometimes work and sometimes they don't. I can ping ```2001:4de0:ac18::1:a:2b``` at all from the Alienwares but from the HP I can. The other IPs will sometime fail the first ping and the rest work.

This happens with Chrome and Firefox both.

**Comment by bezin** [comment] 2022-03-01 08:57
> I'm indirectly having this issue too, trying to access the [James Webb Space Telescope site](https://webb.nasa.gov/content/webbLaunch/whereIsWebb.html?units=metric), and it's failing to load JQuery
This site is broken for me, too.

> Putting the IPv4s in the HOSTS file allows me to connect.
Can confirm that.

> They both have a Killer(R) Wi-Fi 6 AX1650x 160MHz Wireless Network Adapter (200NGW).
I have this trouble with an Dell XPS 13, also using a Killer Wireless Network Adapter, though it is another model (n/a/ac 1435)

**Comment by oppipp** [comment] 2022-03-01 12:14
I'm also an Alienware m17 R2 with a Killer E3000 2.5 Gigabit Ethernet Controller.

**Comment by MackSix** [comment] 2022-03-01 13:40
This also with happens:

https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js
https://cdn.fluidplayer.com/v2/current/fluidplayer.min.css

They are setup on Highwinds CDN like code.jquery.com is.

**Comment by MackSix** [comment] 2022-03-02 23:42
Dell Engineers are looking at this, but since then, 

Since, I got with their tech support, I have fount problems with this URL https://www.t-mobile.com 

nslookup www.t-mobile.com
Server:  dsldevice6.attlocal.net
Address:  2600:1700:da00:2b80::1

Non-authoritative answer:
Name:    7cfz4.x.incapdns.net
Addresses:  2a02:e980:b1::b0
          45.60.11.176
Aliases:  www.t-mobile.com

It will load if I reload it several times. It will then work until I delete the browser file cache and the cookies for it.

**Comment by sprestel** [comment] 2022-03-03 12:35
+1

**Comment by MackSix** [comment] 2022-03-04 02:28
UPDATE: 

Dell Engineers say the hardware works fine and they say I should call software support. 

They also said to use ethernet, but this same problem occurs with the ethernet on both Dell desktops too. The R10 (Windows 11) has the Killer E2600 Gigabet Ethernet Controller and the R11 (Windows 10) has the Killer E3000 Gigabit Ethernet Controller. 

I have an ARRIS W210-700 DSL Residential Gateway from AT&T. 

I tried a fairly new HP laptop that has an Intel Wi-Fi 6 AX201 and it works fine. 

I will work on this further to try and find a solution.

**Comment by MackSix** [comment] 2022-03-05 06:10
Good news!

After spending days on this, I finally found the problem. Even if you have no Killer Control center or uninstalled it, and completely remove the Intel Killer Wi-Fi and Ethernet drivers, there is left a service that starts called "Killer Network Services." Run services.msc and find it running. Kill it and set it to manual or disable it. 

This junk was installed from Windows Update even!  So even if you install fresh version, it installs this stuff. I tried to set the update policy through gpedit.msc to "2. = Notify before downloading and installing any updates" and Microsoft still installed this malware!

Enjoy your computer again!

**Comment by sazzy4o** [comment] 2022-03-30 21:05
I had the same issue on a Dell Laptop

I was able to solve the issues by turning off `Killer Prioritization Engine` in `Killer Control Center`:
![image](https://user-images.githubusercontent.com/10637549/160930738-5370ed1f-4df8-409d-8265-596caff89180.png)

**Comment by MackSix** [comment] 2022-03-30 22:12
> I had the same issue on a Dell Laptop
> 
> I was able to solve the issues by turning off `Killer Prioritization Engine` in `Killer Control Center`: ![image](https://user-images.githubusercontent.com/10637549/160930738-5370ed1f-4df8-409d-8265-596caff89180.png)

Yup, that works too. There is a thread going on Itel support forums here. They seem to be more interested in the problem than Dell was. https://community.intel.com/t5/Wireless/Killer-Network-Service-preventing-connection-to-some-websites/m-p/1366144#M40830

**Comment by Krinkle** [comment] 2022-03-30 23:03
Thanks everyone. I'm glad a solution was found for your cases.

@Eahlstan and others:  If you're still able to reproduce this issue and have ruled out any network middleware you run as possible cause, let me know. The fine folks from StackPath CDN did not find any cause on their end so far. In a week or so I'll close this issue and the upstream support ticket. Feel free to comment any time aferward or file a new issue. It's never too late :)

**Comment by data-leon** [comment] 2022-04-03 20:41
> I had the same issue on a Dell Laptop
> 
> I was able to solve the issues by turning off `Killer Prioritization Engine` in `Killer Control Center`: ![image](https://user-images.githubusercontent.com/10637549/160930738-5370ed1f-4df8-409d-8265-596caff89180.png)

Thank you for the screenshot, it did solve the problem for one of my clients!

**Comment by specialtrevor** [comment] 2022-04-05 08:58
THANK YOU ALL! Had the same issue with my Dell XPS (for jquery and a couple of other sites more recently) and I knew that when my laptop BSOD it was related to this Killer garbage but had never actually run it. Appreciated.

**Closed** 2022-04-06 21:46 UTC

**Comment by bezin** [comment] 2022-04-07 09:43
Thanks for letting us discuss (and solve) this issue here, even though it was unrelated to your website after all 👍
